class GZC_EventHandler : StaticEventHandler
{
	Dictionary EffectProperties;
	Array<Class<GZC_Effect> > effects;
	Array<Class<GZC_Effect> > history;
	Array<GZC_Effect> active;
	Array<String> classnames;
	
	double time;
	double timelimit;
	
	override void OnRegister()
	{
		console.printf("Let's make some noise");
	
		effects.clear();
		active.clear();
		history.clear();
		classnames.clear();
		
		foreach (classtype : AllClasses)
		{
			if (!(classtype is "GZC_Effect")) continue;
			
			string classname = classtype.getClassName();
			if (classname == "GZC_Effect") continue;
			
			GZC_Effect def = GZC_Effect(new(classtype));
			def.init();
			
			if (def.ignore) continue;
			
			class<GZC_Effect> effect = def.getClass();
			effects.push(effect);
			classnames.push(classname.makeUpper());
			
			def.destroy();
		}
		
		console.printf(classnames.size() .. " Effects registered");
		
		//Active seed will launch with -1 if this isn't first set
		let cvarseed = Cvar.getCvar('GZC_ActiveSeed');
		int rng = int(frandom(0, 1) * 0x7FFFFFFF);
		cvarseed.setInt(rng);
		
		EffectProperties = Dictionary.fromString(Cvar.getCvar("GZC_EffectProperties").getString());
	}

	override void NewGame()
	{
		GZC_ShaderEffect.DisableShaders();
		
		let debug = Cvar.getCvar('GZC_LastRolledEffect');
		debug.setString("none");
		
		updateSeed();
	}
	
	override void WorldTick()
	{
		switch (gamestate)
		{
			case GS_TitleLevel:
			default:
				return;
			case GS_Level:
			
				timelimit = 35 * Cvar.getCvar('GZC_TimerDuration').getInt();
				
				int hl = 0;
				foreach (player : players)
				{
					if (!player.mo) continue;
					hl += player.health;
				}
				if (hl <= 0) return;
				if (cc_check()) return;
			
				processConsole();
				tickEvents();
				advanceMainTimer();
				advanceEffectTimers();
				clearDeadEffects();
				
				break;
		}
	}
	
	//Corruption cards check
	bool cc_check()
	{
		name cc_class = 'CCards_Global';
		Class<Thinker> cc_instance = cc_class;
		if (!cc_instance) return false;
		else
		{
			let pinfo = players[0];
			if (pinfo.cheats & CF_TOTALLYFROZEN) return true;
		}
		
		return false;
	}
	
	override void WorldThingDied(WorldEvent _event)
	{
		ThinkerIterator it = ThinkerIterator.create("GZC_Effect");
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.life > effect.duration) continue;
			effect.onWorldThingDied(_event);
		}
	}
	
	override void WorldLoaded(WorldEvent _event)
	{
		updateSeed();
		
		GZC_ShaderEffect.DisableShaders();
		ThinkerIterator sh = ThinkerIterator.create('GZC_ShaderEffect');
		GZC_ShaderEffect se;
		while (se = GZC_ShaderEffect(sh.next())) se.onOpen();
	
		if (_event.isSaveGame) return; //Only call onWorldLoad when it's a new map
	
		ThinkerIterator it = ThinkerIterator.create("GZC_Effect");
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.life > effect.duration) continue;
			effect.onWorldLoad(_event);
		}
	}
	
	override void WorldThingSpawned(WorldEvent _event)
	{
		foreach(effect : active)
		{
			if (effect.life > effect.duration) continue;
			effect.onWorldThingSpawn(_event);
		}
	}
	
	override void WorldLinePreActivated(WorldEvent _event)
	{
		foreach(effect : active)
		{
			if (effect.life > effect.duration) continue;
			effect.onWorldLinePreActivated(_event);
		}
	}
	
	override void RenderOverlay(RenderEvent _event)
	{
		
		foreach(effect : active)
		{
			if (effect.life > effect.duration) continue;
			effect.drawEffect(_event);
		}
	
	}
	
	override bool InputProcess(InputEvent _event)
	{
		bool result = false;
		
		foreach(effect : active)
		{
			if (effect.life > effect.duration) continue;
			bool value = effect.onInputProcess(_event);
			if (value) result = true;
		}
		
		let bind = Bindings.GetBinding(_event.keyscan);
		
		return result;
	}
	
	override void uiTick()
	{
		switch (gamestate)
		{
			case GS_TitleLevel:
			default:
				return;
			case GS_Level:
				
				foreach(effect : active)
				{
					if (effect.life > effect.duration) continue;
					effect.onUiTick();
				}
			
				break;
		}
	}
	
	override bool WorldHitscanPreFired(WorldEvent _event)
	{
		bool result;
		
		foreach(effect : active)
		{
			if (effect.life > effect.duration) continue;
			bool value = effect.onWorldHitscanPreFired(_event);
			if (value) result = value;
		}
		
		return result;
	}
	
	//Purity checkers. If any mods are found, this disables incompatible effects
	//from being rolled.
	
	override void PlayerSpawned(PlayerEvent _event)
	{
		if (_event.playernumber != 0) return;
	
		let player = players[_event.playernumber].mo;
		
		if (!(player is 'GZC_PlayerClass'))
		{
			Cvar.getCvar("GZC_PurePlayer").setBool(false);
		}
	}
	
	override void CheckReplacement(ReplaceEvent _event)
	{
		if (_event.replacement)
		{
			if (_event.replacee is "weapon")
			{
				if (!(_event.replacement is "GZC_ChaosWeapon"))
				{
					Cvar.getCvar("GZC_PureWeapons").setBool(false);
				}
			}
			else if (_event.replacee is "PlayerPawn")
			{
				if (!(_event.replacement is "GZC_PlayerClass"))
				{
					Cvar.getCvar("GZC_PurePlayer").setBool(false);
				}
			}
			else
			{
				let def = getDefaultByType(_event.replacee);
				if (def.painchance) //Hacky check, but default decorations don't have a painchance
				{
					if (!(_event.replacement is "GZC_ChaosMonster"))
					{
						Cvar.getCvar("GZC_PureActors").setBool(false);
					}
				}
			}
		}
	}
	
	void processConsole()
	{
		if (cvar.getCvar('gzc_addeffect') && cvar.getCvar('gzc_addeffect').getString() != "")
		{
			string value = cvar.getCvar('gzc_addeffect').getString();
			cvar.getCvar('gzc_addeffect').setString("");
			foreach (classname : classnames)
			{
				string cname = classname.makeUpper();
				string input = value.makeUpper();
				int index = cname.indexOf(input);
			
				if (index != -1)
				{
					let player = players[0].mo;
					
					player.giveInventory(cname, 1);
					let effect = GZC_Effect(player.FindInventory(cname));
					addEffectToHistory(effect.getClass());
					effect.onOpen();
					
					if (!effect.verify())
					{
						console.printf('Effect failed verification');
					}
					
					return;
				}
			}
			console.printf('No effect ' .. value .. ' found');
		}
	}
	
	void tickEvents()
	{
		ThinkerIterator it = ThinkerIterator.create("GZC_Effect");
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.closed) continue;
			effect.onWorldTick();
		}
	}
	
	void advanceMainTimer()
	{
		if (Cvar.getCvar("gzc_pausemaintimer").getBool()) return;
		
		int effectcount = GZC_Effect.getEffectCount();
		int limit = Cvar.getCvar('GZC_MaxEffects').getInt();
		
		if (effectcount >= limit && limit != 0) return;
	
		let player = players[0].mo;
	
		double timerrate = calculateTimeRate();

		foreach (effect : active)
		{
			if (effect is 'GZC_TimerRunsOnKills')
			{
				timerrate = 0;
				break;
			}
		}
		
		time += timerrate;
		
		if (time >= timelimit)
		{
			time -= timelimit;
			giveEffect();
		}
	}
	
	void advanceEffectTimers()
	{
		if (Cvar.getCvar("gzc_pauseeffecttimer").getBool()) return;
		
		let player = players[0].mo;
		
		double effectrate = calculateEffectRate();
		
		foreach (effect : active)
		{
			if (effect is 'GZC_TimerRunsOnKills')
			{
				effectrate = 0;
				break;
			}
		}
		
		ThinkerIterator it = ThinkerIterator.create("GZC_Effect");
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			effect.advanceEffect(effectrate);
			if (effect.closed) continue;
			if (effect.life >= effect.duration)
			{
				effect.onClose();
				effect.closed = true;
			}
		}
	}
	
	void clearDeadEffects()
	{
		let player = players[0].mo;
	
		ThinkerIterator it = ThinkerIterator.create("GZC_Effect");
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.deleteme)
			{
				effect.destroy();
			}
		}
	}
	
	double calculateTimeRate()
	{
		double rate = 1.0;
		
		ThinkerIterator it = ThinkerIterator.create("GZC_TimerEffect");
		GZC_TimerEffect effect;
		
		while (effect = GZC_TimerEffect(it.next()))
		{
			if (effect.ignore) continue;
			if (effect.closed) continue;
			rate *= effect.value;
		}
		
		return rate;
	}
	
	double calculateEffectRate()
	{
		double rate = 1.0;
		
		ThinkerIterator it = ThinkerIterator.create("GZC_EffectModifier");
		GZC_EffectModifier effect;
		
		while (effect = GZC_EffectModifier(it.next()))
		{
			if (effect.ignore) continue;
			if (effect.closed) continue;
			rate *= effect.value;
		}
		
		return rate;
	}
	
	void giveEffect(Bool _awarded = false)
	{
		int safety = 0;
	
		while (true)
		{
			++safety;
			if (safety >= 500) 
			{
				console.printf('I had to break!');
				break;
			}
			
			let effect = effects[random[GZ_Chaos](0, effects.size() - 1)];
			console.printf("Attempting to add: " .. effect.getClassName());

			if (history.size() != 0)
			{
				console.printf("Checking history...");
				bool match = false;
				foreach (prev : history)
				{
					if (prev == effect)
					{
						match = true;
						break;
					}
				}
				if (match) continue;
			}
			
			if (active.size() != 0)
			{
				console.printf("Checking active...");
				bool match = false;
				foreach (eff : active)
				{
					console.printf(" -> Comparing " .. eff.getClassName());
					if (eff.getClassName() == effect.getClassName())
					{
						match = true;
						break;
					}
				}
				if (match) 
				{
					console.printf(" -> Matched, trying new effect...");
					continue;
				}
			}
			
			let rolled = GZC_Effect(new(effect));
			rolled.init();
			
			console.printf("Verifying...");
			if (!rolled.verify())
			{
				rolled.destroy();
				console.printf("Verification failed, trying new effect...");
				continue;
			}
			
			addEffectToHistory(effect);
			active.push(rolled);
			rolled.awarded = _awarded;
			
			break;
		}
	}
	
	void addEffectToHistory(Class<GZC_Effect> _effect)
	{
		history.insert(0, _effect);
		history.resize(Cvar.getCvar('GZC_MemoryBuffer').getInt());
	}
	
	void updateSeed()
	{
		let useseed = Cvar.getCvar('GZC_UseSeed').getBool();
		
		int seedvalue;
		
		if (useseed)
		{
			seedvalue = int(name(Cvar.getCvar('GZC_UserSeedValue').getString()));
			if (Cvar.getCvar('GZC_UseRandomSeed').getBool())
			{
				seedvalue = int(frandom[GZ_Chaos](0, 1) * 0x7FFFFFFF);
			}
		}
		else
		{
			seedvalue = int(frandom[GZ_Chaos](0, 1) * 0x7FFFFFFF);
		}
		
		SetRandomSeed[GZ_Chaos](seedvalue);
		Cvar.getCvar('GZC_ActiveSeed').setInt(seedvalue);
	}
}