class GZC_ZombiemenFireShotguns : GZC_Effect
{
	default
	{
		GZC_Effect.title "Zombiemen fire shotguns";
		GZC_Effect.duration 35 * 60 * 3;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;
		if (_event.attackpufftype == "GZC_BulletPuff") return false;
		
		_event.thing.A_CustomBulletAttack(22.5, 0, 3, random(1,5)*3, "GZC_BulletPuff", 0, CBAF_NORANDOM);
		_event.thing.A_PlaySound("shotguy/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemenFireFireballs : GZC_Effect
{
	default
	{
		GZC_Effect.title "Zombiemen fire shotguns";
		GZC_Effect.duration 35 * 60 * 3;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_TroopAttack();
		_event.thing.A_PlaySound("doomimp/attack", CHAN_WEAPON);
		
		return true;
	}
}