class GZC_ZombiemanAttackEffect : GZC_Effect
{
	Default
	{
		GZC_Effect.ignore true;
	}
	
	override bool verify()
	{
		return mapHasThisActor("Zombieman");
	}
}

class GZC_ZombiemanRepeater : GZC_Effect
{
	default
	{
		GZC_Effect.title "Zombiemen repeat fire";
		GZC_Effect.duration 35 * 60 * 3;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		let mon = _event.thing;
		
		if (mon.isVisible(mon.target, true) && mon.target.health > 0)
		{
			mon.setStateLabel("Missile");
			return false;
		}
		else
		{
			int rnd = random(0, 255);
			if (rnd < 40) mon.SetStateLabel("See");
			else
			{
				mon.setStateLabel("Missile");
				return false;
			}
		}
		
		return true;
	}
	
	override bool verify()
	{
		return mapHasThisActor("Zombieman");
	}
}

class GZC_ZombiemenFireShotguns : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen fire shotguns";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;
		if (_event.attackpufftype == "GZC_BulletPuff") return false;
		
		_event.thing.A_CustomBulletAttack(22.5, 0, 3, random(1,5)*3, "GZC_BulletPuff", 0, CBAF_NORANDOM);
		_event.thing.A_PlaySound("shotguy/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemenFireFireballs : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen shoot fireballs";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_TroopAttack();
		_event.thing.A_PlaySound("doomimp/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemenFireBaronballs : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen fire Baron balls";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_BruisAttack();
		_event.thing.A_PlaySound("baron/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFirePlasma : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen fire plasma";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_BSPIAttack();
		_event.thing.A_PlaySound("baby/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireMissiles : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen fire missiles";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_SkelMissile();
		_event.thing.A_PlaySound("skeleton/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireRockets : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen fire rockets";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_CyberAttack();
		_event.thing.A_PlaySound("weapons/rocklf", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireCacoballs : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen fire Caco-balls";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_HeadAttack();
		_event.thing.A_PlaySound("caco/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireLostSouls : GZC_ZombiemanAttackEffect
{
	default
	{
		GZC_Effect.title "Zombiemen fire Lost Souls";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_PainAttack();
		
		return true;
	}
}