class GZC_ZombiemanAttackEffect : GZC_Effect
{
	override void init()
	{
		ignore = true;
	}
	
	override bool verify()
	{
		if (!mapHasThisActor("Zombieman")) return false;
		else return Super.verify();
	}
}

class GZC_ZombiemanRepeater : GZC_Effect
{
	override void init()
	{
		title = "Zombiemen repeat fire";
		desc = title;
		duration = 35 * 60 * 3;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		let mon = _event.thing;
		
		if (mon.isVisible(mon.target, true) && mon.target.health > 0)
		{
			mon.setStateLabel("Missile");
			return false;
		}
		else
		{
			int rnd = random(0, 255);
			if (rnd < 40) mon.SetStateLabel("See");
			else
			{
				mon.setStateLabel("Missile");
				return false;
			}
		}
		
		return true;
	}
	
	override bool verify()
	{
		if (!mapHasThisActor("Zombieman")) return false;
		else return Super.verify();
	}
}

class GZC_ZombiemenFireShotguns : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen fire shotguns";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;
		if (_event.attackpufftype == "GZC_BulletPuff") return false;
		
		_event.thing.A_CustomBulletAttack(22.5, 0, 3, random(1,5)*3, "GZC_BulletPuff", 0, CBAF_NORANDOM);
		_event.thing.A_StartSound("shotguy/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemenFireFireballs : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen shoot fireballs";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_TroopAttack();
		_event.thing.A_StartSound("doomimp/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemenFireBaronballs : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen fire Baron balls";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_BruisAttack();
		_event.thing.A_StartSound("baron/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFirePlasma : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen fire plasma";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_BSPIAttack();
		_event.thing.A_StartSound("baby/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireMissiles : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen fire missiles";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_SkelMissile();
		_event.thing.A_StartSound("skeleton/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireRockets : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen fire rockets";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_CyberAttack();
		_event.thing.A_StartSound("weapons/rocklf", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireCacoballs : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen fire Caco-balls";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_HeadAttack();
		_event.thing.A_StartSound("caco/attack", CHAN_WEAPON);
		
		return true;
	}
}

class GZC_ZombiemanFireLostSouls : GZC_ZombiemanAttackEffect
{
	override void init()
	{
		title = "Zombiemen fire Lost Souls";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "ZombieMan")) return false;

		_event.thing.A_PainAttack();
		
		return true;
	}
}