class GZC_CacodemonAttackEffect : GZC_Effect
{
	override void init()
	{
		ignore = true;
	}
	
	override bool verify()
	{
		if (!mapHasThisActor("Cacodemon")) return false;
		else return Super.verify();
	}
}

class GZC_CacodemonRepeater : GZC_Effect
{
	override void init()
	{
		title = "Cacodemons repeat fire";
		desc = title;
		duration = 35 * 60 * 3;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		
		if (caco.isVisible(caco.target, true) && caco.target.health > 0)
		{
			caco.setStateLabel("Missile");
		}
		else
		{
			int rnd = random(0, 255);
			if (rnd < 40) caco.SetStateLabel("See");
			else
			{
				caco.setStateLabel("Missile");
			}
		}
	}
	
	override bool verify()
	{
		if (!mapHasThisActor("Cacodemon")) return false;
		else return Super.verify();
	}
}

class GZC_CacodemonFireBullets : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon fire bullets";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_PosAttack();
		caco.A_StartSound("grunt/attack");
		
		_event.thing.destroy();
	}
}

class GZC_CacodemonFireShotgun : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon fire shotguns";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_CPosAttack();
		caco.A_StartSound("shotguy/attack");
		
		_event.thing.destroy();
	}
}

class GZC_CacodemonFireBaronBalls : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon fire Baron Balls";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_BruisAttack();
		caco.A_StartSound("baron/attack");
		
		_event.thing.destroy();
	}
}

class GZC_CacodemonFirePlasma : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon fire plasma";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_BSpiAttack();
		caco.A_StartSound("baby/attack");
		
		_event.thing.destroy();
	}
}

class GZC_CacodemonFireMissiles : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon fire missiles";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_SkelMissile();
		caco.A_StartSound("skeleton/attack", CHAN_WEAPON);
		
		_event.thing.destroy();
	}
}

class GZC_CacodemonFireRockets : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon fire Rockets";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_CyberAttack();
		caco.A_StartSound("weapons/rocklf", CHAN_WEAPON);
		
		_event.thing.destroy();
	}
}

class GZC_CacodemonShootFireballs : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon shoot fireballs";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_TroopAttack();
		caco.A_StartSound("doomimp/attack", CHAN_WEAPON);
		
		_event.thing.destroy();
	}
}

class GZC_CacodemonFireLostSouls : GZC_CacodemonAttackEffect
{
	override void init()
	{
		title = "Cacodemon fire Lost Souls";
		desc = title;
		duration = 35 * 60 * 3;
		ignore = false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "CacodemonBall")) return;
		
		let caco = _event.thing.target;
		caco.A_PainAttack();
		
		_event.thing.destroy();
	}
}