class GZC_DoomImpAttackEffect : GZC_Effect
{
	Default
	{
		GZC_Effect.ignore true;
	}
	
	override bool verify()
	{
		return mapHasThisActor("DoomImp");
	}
}

class GZC_DoomImpRepeater : GZC_Effect
{
	default
	{
		GZC_Effect.title "Imps repeat fire";
		GZC_Effect.duration 35 * 60 * 3;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		
		if (imp.isVisible(imp.target, true) && imp.target.health > 0)
		{
			imp.setStateLabel("Missile");
		}
		else
		{
			int rnd = random(0, 255);
			if (rnd < 40) imp.SetStateLabel("See");
			else
			{
				imp.setStateLabel("Missile");
			}
		}
	}
}

class GZC_DoomImpFireBullets : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire bullets";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_PosAttack();
		imp.A_StartSound("grunt/attack");
		
		_event.thing.destroy();
	}
}

class GZC_DoomImpFireShotgun : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire shotguns";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_CPosAttack();
		imp.A_StartSound("shotguy/attack");
		
		_event.thing.destroy();
	}
}

class GZC_DoomImpFireBaronBalls : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire Baron Balls";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_BruisAttack();
		imp.A_StartSound("baron/attack");
		
		_event.thing.destroy();
	}
}

class GZC_DoomImpFirePlasma : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire plasma";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_BSpiAttack();
		imp.A_StartSound("baby/attack");
		
		_event.thing.destroy();
	}
}

class GZC_DoomImpFireMissiles : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire missiles";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_SkelMissile();
		imp.A_StartSound("skeleton/attack", CHAN_WEAPON);
		
		_event.thing.destroy();
	}
}

class GZC_DoomImpFireRockets : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire Rockets";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_CyberAttack();
		imp.A_StartSound("weapons/rocklf", CHAN_WEAPON);
		
		_event.thing.destroy();
	}
}

class GZC_DoomImpFireCacoballs : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire Caco-balls";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_HeadAttack();
		imp.A_StartSound("caco/attack", CHAN_WEAPON);
		
		_event.thing.destroy();
	}
}

class GZC_DoomImpFireLostSouls : GZC_DoomImpAttackEffect
{
	default
	{
		GZC_Effect.title "Imps fire Lost Souls";
		GZC_Effect.duration 35 * 60 * 3;
		GZC_Effect.ignore false;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "DoomImpBall")) return;
		
		let imp = _event.thing.target;
		imp.A_PainAttack();
		
		_event.thing.destroy();
	}
}