class GZC_Shrooms : GZC_ShaderEffect
{
	//Based on an actual shroom trip I had!
	override void init()
	{
		title = "Vibin on the cybin";
		desc = "Turns on a psychedelic shader";
		duration = 35 * 60;
		ignore = false;
	}
	
	override void onOpen()
	{
		PPShader.SetEnabled("shrooms", true);
	}
	
	override void onClose()
	{
		PPShader.SetEnabled("shrooms", false);
	}
	
	override void onWorldTick()
	{
		PPShader.SetUniform1i("shrooms", "iTime", gametic);
	}
}

class GZC_MSDOSMode : GZC_ShaderEffect
{
	override void init()
	{
		title = "MS-DOS";
		desc = "Tuens on a shader that imitates the MS-DOS resolution";
		duration = 35 * 60;
		ignore = false;
	}
	
	override void onOpen()
	{
		PPShader.SetEnabled("lowres", true);
		PPShader.SetUniform2f("lowres", "iResolution", (Screen.getWidth(), Screen.getHeight()));
	}
	
	override void onClose()
	{
		PPShader.SetEnabled("lowres", false);
	}
}

class GZC_GameboyMode : GZC_ShaderEffect
{
	override void init()
	{
		title = "Doom for the Gameboy";
		desc = "Turns on a shader that converts all color into the GB's color palette";
		duration = 35 * 60;
		ignore = false;
	}
	
	override void onOpen()
	{
		PPShader.SetEnabled("gb_shader", true);
	}
	
	override void onClose()
	{
		PPShader.SetEnabled("gb_shader", false);
	}
	
	override void onWorldTick()
	{
		PPShader.SetUniform2f("gb_shader", "iResolution", (Screen.getWidth(), Screen.getHeight()));
	}
}

class GZC_YouNeedGlasses : GZC_ShaderEffect
{
	override void init()
	{
		title = "You need glasses";
		desc = "Turns on a shader that makes everything blurry";
		duration = 35 * 60;
		ignore = false;
	}
	
	override void onOpen()
	{
		PPShader.SetEnabled("blur", true);
	}
	
	override void onClose()
	{
		PPShader.SetEnabled("blur", false);
	}
	
	override void onWorldTick()
	{
		PPShader.SetUniform2f("blur", "iResolution", (Screen.getWidth(), Screen.getHeight()));
	}
}

class GZC_LiquidQuake : GZC_ShaderEffect
{
	override void init()
	{
		title = '*slime';
		desc = "Turns on a shader that imitates Quake's liquid animation";
		duration = 35 * 60;
		ignore = false;
	}
	
	override void onOpen()
	{
		PPShader.SetEnabled("liquid", true);
	}
	
	override void onClose()
	{
		PPShader.SetEnabled("liquid", false);
	}
	
	override void onWorldTick()
	{
		PPShader.SetUniform1i("liquid", "iTime", gametic);
	}
}