class GZC_NoStrafing : GZC_Effect
{
	override void init()
	{
		title = "Disable strafing";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+moveleft" || bind ~== "+moveright") return true;
		
		return false;
	}
}

class GZC_NoStrafingLeft : GZC_Effect
{
	override void init()
	{
		title = "Disable strafing left";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+moveleft") return true;
		
		return false;
	}
}

class GZC_NoStrafingRight : GZC_Effect
{
	override void init()
	{
		title = "Disable strafing right";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+moveright") return true;
		
		return false;
	}
}

class GZC_NoForwardBackwards : GZC_Effect
{
	override void init()
	{
		title = "Disable forward/backward";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+forward" || bind ~== "+back") return true;
		
		return false;
	}
}

class GZC_NoForward : GZC_Effect
{
	override void init()
	{
		title = "Disable moving forward";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+forward") return true;
		
		return false;
	}
}

class GZC_NoBackwards : GZC_Effect
{
	override void init()
	{
		title = "Disable moving backward";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+back") return true;
		
		return false;
	}
}

class GZC_NoWeaponScrolling : GZC_Effect
{
	override void init()
	{
		title = "No weapon scrolling";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "weapprev" || bind ~== "weapnext") return true;
		
		return false;
	}
}

class GZC_NoJumping : GZC_Effect
{
	override void init()
	{
		title = "Disabled jumping";
		duration = 35 * 60 * 2;
	}
	
	override bool verify()
	{
		if (!level.isJumpingAllowed()) return false;
		
		return super.verify();
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+jump") return true;
		
		return false;
	}
}

class GZC_NoCrouching : GZC_Effect
{
	override void init()
	{
		title = "Disabled crouching";
		duration = 35 * 60 * 2;
	}
	
	override bool verify()
	{
		if (!level.IsCrouchingAllowed()) return false;
		
		return super.verify();
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+crouch") return true;
		
		return false;
	}
}

class GZC_SwapFiringMode : GZC_Effect
{
	override void init()
	{
		title = "Swapped firing input";
		duration = 35 * 60 * 2;
	}
	
	int buttons;
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		
		if (bind ~== "+attack" || bind ~== "+altattack")
		{
			if (bind ~== "+attack")
			{
				if (_event.type == InputEvent.Type_KeyDown) setFlag(BT_ALTATTACK);
				else if (_event.type == InputEvent.Type_KeyUp) unsetFlag(BT_ALTATTACK);
			}
			
			if (bind ~== "+altattack")
			{
				if (_event.type == InputEvent.Type_KeyDown) setFlag(BT_ATTACK);
				else if (_event.type == InputEvent.Type_KeyUp) unsetFlag(BT_ATTACK);
			}
			
			return true;
		}
		
		return false;
	}
	
	override void onUiTick()
	{
		checkPlayerFire();
	}
	
	play void checkPlayerFire() const
	{
		foreach (iplayer : players)
		{
			let player = iplayer;
			if (!player.mo) continue;
			player.cmd.buttons |= buttons;
		
			player.mo.checkWeaponFire();
		}
	}
	
	play void setFlag(Int _flag) const
	{
		buttons |= _flag;
	}
	
	play void unsetFlag(Int _flag) const
	{	
		buttons &= ~(_flag);
	}
}

class GZC_InvertedMouselook : GZC_Effect
{
	override void init()
	{
		title = "Inverted Mouselook";
		duration = 35 * 60 * 2;
	}
	
	override bool verify()
	{
		if (!level.IsFreelookAllowed()) return false;
		
		return super.verify();
	}
	
	override void onUiTick()
	{
		updatePlayerPitch();
	}
	
	play void updatePlayerPitch() const
	{
		foreach (iplayer : players)
		{
			let player = iplayer;
			if (!player.mo) continue;
			player.cmd.pitch *= -1.0;
		
			player.mo.CheckPitch();
		}
	}
}

/*class GZC_KeyboardControls : GZC_Effect
{
	//200 up arrow
	//208 down arrow
	//203 left
	//205 right

	override void init()
	{
		title = "Keyboard only!";
		duration = 35 * 60 * 2;
	}
	
	int buttons;
	
	override bool onInputProcess(InputEvent _event)
	{
		switch (_event.keyscan)
		{
			case 200:
				if (_event.type == InputEvent.Type_KeyDown) setFlag(BT_FORWARD);
				else if (_event.type == InputEvent.Type_KeyUp) unsetFlag(BT_FORWARD);
				break;
		}
		
		return false;
	}
	
	override void onUiTick()
	{
		setPlayerFlags();
	}
	
	play void setPlayerFlags() const
	{
		let player = players[consoleplayer];
		player.cmd.buttons |= buttons;
		
		player.mo.PlayerThink();
	}
	
	play void setFlag(Int _flag) const
	{
		buttons |= _flag;
	}
	
	play void unsetFlag(Int _flag) const
	{	
		buttons &= ~(_flag);
	}
}*/