class GZC_GoodHeadphones : GZC_Effect
{
	override void init()
	{
		title = "Noise Canceling Headphones";
		duration = 35 * 60 * 5;
	}
	
	override void onOpen()
	{
		ThinkerIterator it = ThinkerIterator.create("Inventory");
		Inventory mo;
		
		while (mo = Inventory(it.next()))
		{
			applyeffect(mo);
		}
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!(_event.thing is "inventory")) return;
		applyeffect(Inventory(_event.thing));
	}
	
	override void onWorldTick()
	{
		S_PauseSound(true, false);
	}
	
	void applyeffect(Inventory _item)
	{
		_item.PickupSound = "";
	}
	
	override void onClose()
	{
		ThinkerIterator it = ThinkerIterator.create("Inventory");
		Inventory mo;
		
		while (mo = Inventory(it.next()))
		{
			let def = getDefaultByType(mo.getClass());
			mo.PickupSound = def.PickupSound;
		}
	}
}

Class GZC_DigDugWalking : GZC_Effect
{
	override void init()
	{
		title = "DIG DUG";
		duration = 35 * 60 * 3;
	}
	
	override void onOpen()
	{
		let player = players[consoleplayer];
		player.mo.S_ChangeMusic('DIGDUG');
	}
	
	override void onWorldLoad(WorldEvent _event)
	{
		let player = players[consoleplayer];
		player.mo.S_ChangeMusic('DIGDUG');
	}
	
	override void onWorldTick()
	{
		let player = players[consoleplayer];
		if (!(player.cmd.buttons & (BT_Forward | BT_Back | BT_Left | BT_Right | BT_MoveLeft | BT_MoveRight)))
		{
			S_PauseSound(false, true);
		}
	}
	
	override void onClose()
	{
		let player = players[consoleplayer];
		player.mo.S_ChangeMusic(Level.music);
	}
}

Class GZC_RandomActorSoundPitch : GZC_Effect
{
	override void init()
	{
		title = "Smack my pitch up";
		duration = 35 * 60 * 3;
	}

	double randomvalue;
	
	override void onWorldTick()
	{
		ThinkerIterator it = ThinkerIterator.create("Actor");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			for (int i = 0; i < 8; ++i)
			{
				mo.A_SoundPitch(i, randomvalue);
			}
		}
	}
	
	override void onWorldThingDied(WorldEvent _event)
	{
		randomvalue = frandom(0.25, 2);
	}
}

Class GZC_TheEddsAreComing : GZC_Effect //More like GZC_Eddffect, hue hue hue
{
	override void init()
	{
		title = "The Edds Are Coming!";
		duration = 35 * 60 * 5;
	}

	override void onOpen()
	{
		startReassignment();
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (_event.thing.bIsmonster) return;
		reassignDeathSound(_event.thing);
	}
	
	override void onWorldLoad(WorldEvent _event)
	{
		startReassignment();
	}
	
	void startReassignment()
	{
		ThinkerIterator it = ThinkerIterator.create("Actor");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			if (!mo.bIsMonster) continue;
			reassignDeathSound(mo);
		}
	}
	
	void reassignDeathSound(Actor _mo)
	{
		_mo.DeathSound = "EEnE/kill";
		_mo.bFullVolDeath = true;
	}
	
	override void onWorldLinePreActivated(WorldEvent _event)
	{
		if (_event.thing is "PlayerPawn")
		{
			PlayerPawn(_event.thing).A_StartSound("EEnE/Line", CHAN_AUTO);
		}
	}
	
	override void onClose()
	{
		ThinkerIterator it = ThinkerIterator.create("Actor");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			if (!mo.bIsMonster) continue;
			
			let def = getDefaultByType(mo.getClass());
			mo.DeathSound = def.DeathSound;
			mo.bFullVolDeath = def.bFullVolDeath;
		}
	}
}

Class GZC_QuipItGood : GZC_Effect
{
	override void init()
	{
		title = "Quip it Good";
		duration = 35 * 60 * 5;
	}

	override void onWorldThingDied(WorldEvent _event)
	{
		if (!_event.thing.bIsMonster) return;
		
		if (_event.thing.target is "PlayerPawn")
		{
			_event.thing.target.A_StartSound("Quip/Quip", CHAN_AUTO);
		}
	}
}

Class GZC_WhipCrack : GZC_Effect
{
	override void init()
	{
		title = "Johnny Test";
		duration = 35 * 60;
	}
	
	Array<int> buttons;
	
	override void onOpen()
	{
		buttons.clear();
		buttons.reserve(16);
		for (int i = 0; i < 16; ++i) buttons[i] = 0;
	}

	override void onWorldLinePreActivated(WorldEvent _event)
	{
		if (_event.thing is "PlayerPawn") _event.thing.A_StartSound("Whip/Crack", CHAN_AUTO);
	}

	override void onWorldThingDied(WorldEvent _event)
	{
		if (_event.thing.target is "PlayerPawn") _event.thing.A_StartSound("Whip/Crack", CHAN_AUTO);
	}

	override void OnWorldTick()
	{
		foreach (iplayer : players)
		{
			if (!iplayer.mo) continue;
			
			if (buttons[iplayer.mo.playernumber()] != iplayer.cmd.buttons) iplayer.mo.A_StartSound("Whip/Crack", CHAN_AUTO);
			buttons[iplayer.mo.playernumber()] = iplayer.cmd.buttons;
		}
	}
}

Class GZC_SetMusicToCursedMidi : GZC_Effect
{
	override void init()
	{
		title = "Cursed music";
		duration = 35 * 30 * 5;
	}
	
	int rng;

	override void onOpen()
	{
		rng = random(0, E_NumSongs - 1);
		applymusic();
	}
	
	override void onWorldLoad(WorldEvent _event)
	{
		applymusic();
	}
	
	void applymusic()
	{
		switch (rng)
		{
			case E_RUNNNN:
				S_ChangeMusic('D_RUNNNN');
				title = "D_RUNNNN";
				break;
			case E_DURGEN:
				S_ChangeMusic('DRGNFRCE');
				title = "TRO DA FER AN DA FWAMES";
				break;
			case E_MEGALO:
				S_ChangeMusic('MEGALODOOMIA');
				title = "Megalodoomia";
				break;
			case E_VENFLOW:
				S_ChangeMusic('EVENFLOW');
				title = "Evenflow (Pearl Jam)";
				break;
			case E_SKRILLEX:
				S_ChangeMusic('SKRILLEX');
				title = "Scary Monsters and Nice Sprites (Skrillex)";
				break;
		}
	}
	
	override void onClose()
	{
		S_ChangeMusic(level.music);
	}
}

enum E_Music
{
	E_RUNNNN,
	E_DURGEN,
	E_MEGALO,
	E_VENFLOW,
	E_SKRILLEX,
	E_NumSongs
}

Class GZC_FakeNotification : GZC_Effect
{
	bool set;
	int ticcount;
	int interval;
	
	override void init()
	{
		title = "Nothing.";
		duration = 35 * 60;
		type = GZC_Instant;
	}
	
	override void onWorldTick()
	{
		if (!set)
		{
			ticcount = gametic;
			interval = random(5, 10);
			set = true;
		}
		if (gametic - ticcount == 35 * interval)
		{
			foreach (iplayer : players)
			{
				if (!iplayer.mo) continue;
				iplayer.mo.A_StartSound("disc/ord", CHAN_AUTO, 0, 1, ATTN_NONE);
			}
			title = "Nothing?";
		}
	}
}