class GZC_StickyKeys : GZC_Effect
{
	String rbind;
	bool decrement;
	
	override void init()
	{
		title = "Sticky keys";
		desc = "A random bind is \"jammed\" and needs to be pressed repeatedly to unjam";
		duration = random(10, 30);
		
		Array<String> binds = {'+use', '+back', '+forward', '+moveleft', '+moveright', '+attack', '+altattack', '+speed'};
		Array<String> probebinds = {'+jump', '+crouch', '+reload'}; //binds the player might not have bound, effect is kinda useless if the player doesn't use these ever
		foreach (pbind : probebinds)
		{
			int a, b;
			[a, b] = Bindings.getKeysForCommand(pbind);
			if (a || b) binds.push(pbind);
		}
		
		rbind = binds[random(0, binds.size() - 1)];
		title = "Press " .. rbind.mid(1, rbind.length()) .. " " .. int(duration - life) .. ' times to unstick...';
	}
	
	override void advanceEffect(Double _amount)
	{
		if (decrement)
		{
			++life;
			if (life < duration) 
			{
				decrement = false;
				title = "Press " .. rbind.mid(1, rbind.length()) .. " " .. int(duration - life) .. ' times to unstick...';
			}
		}
		
		if (life >= duration + (35 * 15))
		{
			deleteme = true;
		}
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		if (deleteme) return false;
		if (_event.type == InputEvent.Type_KeyDown)
		{
			let bind = Bindings.getBinding(_event.KeyScan);
			if (bind ~== rbind) 
			{
				decrlife();
				return true;
			}
		}
		
		return false;
	}
	
	play void decrlife() unsafe(const)
	{
		decrement = true;
	}
}

class GZC_NoStrafing : GZC_Effect
{
	override void init()
	{
		title = "Disable strafing";
		desc = "Left and right strafing input disabled";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+moveleft" || bind ~== "+moveright") return true;
		
		return false;
	}
}

class GZC_NoStrafingLeft : GZC_Effect
{
	override void init()
	{
		title = "Disable strafing left";
		desc = "Left strafing input disabled";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+moveleft") return true;
		
		return false;
	}
}

class GZC_NoStrafingRight : GZC_Effect
{
	override void init()
	{
		title = "Disable strafing right";
		desc = "Right strafing input disabled";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+moveright") return true;
		
		return false;
	}
}

class GZC_NoForwardBackwards : GZC_Effect
{
	override void init()
	{
		title = "Disable forward/backward";
		desc = "Forward and backward input disabled";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+forward" || bind ~== "+back") return true;
		
		return false;
	}
}

class GZC_NoForward : GZC_Effect
{
	override void init()
	{
		title = "Disable moving forward";
		desc = "Forward input disabled";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+forward") return true;
		
		return false;
	}
}

class GZC_NoBackwards : GZC_Effect
{
	override void init()
	{
		title = "Disable moving backward";
		desc = "Backward movement disabled";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+back") return true;
		
		return false;
	}
}

class GZC_NoWeaponScrolling : GZC_Effect
{
	override void init()
	{
		title = "No weapon scrolling";
		desc = "Next and Previous weapon input disabled";
		duration = 35 * 60 * 2;
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "weapprev" || bind ~== "weapnext") return true;
		
		return false;
	}
}

class GZC_NoJumping : GZC_Effect
{
	override void init()
	{
		title = "Disabled jumping";
		desc = "Jumping input disabled (if map allows it)";
		duration = 35 * 60 * 2;
	}
	
	override bool verify()
	{
		if (!level.isJumpingAllowed()) return false;
		
		return super.verify();
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+jump") return true;
		
		return false;
	}
}

class GZC_NoCrouching : GZC_Effect
{
	override void init()
	{
		title = "Disabled crouching";
		desc = "Crouching input disabled (if map allows it)";
		duration = 35 * 60 * 2;
	}
	
	override bool verify()
	{
		if (!level.IsCrouchingAllowed()) return false;
		
		return super.verify();
	}
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		if (bind ~== "+crouch") return true;
		
		return false;
	}
}

class GZC_SwapFiringMode : GZC_Effect
{
	override void init()
	{
		title = "Swapped firing input";
		desc = "Forces primary fire to perform alt fire, and alt fire to perform primary fire";
		duration = 35 * 60 * 2;
	}
	
	int buttons;
	
	override bool onInputProcess(InputEvent _event)
	{
		let bind = Bindings.getBinding(_event.KeyScan);
		
		if (bind ~== "+attack" || bind ~== "+altattack")
		{
			if (bind ~== "+attack")
			{
				if (_event.type == InputEvent.Type_KeyDown) setFlag(BT_ALTATTACK);
				else if (_event.type == InputEvent.Type_KeyUp) unsetFlag(BT_ALTATTACK);
			}
			
			if (bind ~== "+altattack")
			{
				if (_event.type == InputEvent.Type_KeyDown) setFlag(BT_ATTACK);
				else if (_event.type == InputEvent.Type_KeyUp) unsetFlag(BT_ATTACK);
			}
			
			return true;
		}
		
		return false;
	}
	
	override void onUiTick()
	{
		checkPlayerFire();
	}
	
	play void checkPlayerFire() Unsafe(const)
	{
		foreach (iplayer : players)
		{
			let player = iplayer;
			if (!player.mo) continue;
			player.cmd.buttons |= buttons;
		
			player.mo.checkWeaponFire();
		}
	}
	
	play void setFlag(Int _flag) Unsafe(const)
	{
		buttons |= _flag;
	}
	
	play void unsetFlag(Int _flag) Unsafe(const)
	{	
		buttons &= ~(_flag);
	}
}

class GZC_InvertedMouselook : GZC_Effect
{
	override void init()
	{
		title = "Inverted Mouselook";
		desc = "Inverts pitch input with freelook (if map allows it)";
		duration = 35 * 60 * 2;
	}
	
	override bool verify()
	{
		if (!level.IsFreelookAllowed()) return false;
		
		return super.verify();
	}
	
	override void onUiTick()
	{
		updatePlayerPitch();
	}
	
	play void updatePlayerPitch() const
	{
		foreach (iplayer : players)
		{
			let player = iplayer;
			if (!player.mo) continue;
			player.cmd.pitch *= -1.0;
		
			player.mo.CheckPitch();
		}
	}
}

/*class GZC_KeyboardControls : GZC_Effect
{
	//200 up arrow
	//208 down arrow
	//203 left
	//205 right

	override void init()
	{
		title = "Keyboard only!";
		duration = 35 * 60 * 2;
	}
	
	int buttons;
	
	override bool onInputProcess(InputEvent _event)
	{
		switch (_event.keyscan)
		{
			case 200:
				if (_event.type == InputEvent.Type_KeyDown) setFlag(BT_FORWARD);
				else if (_event.type == InputEvent.Type_KeyUp) unsetFlag(BT_FORWARD);
				break;
		}
		
		return false;
	}
	
	override void onUiTick()
	{
		setPlayerFlags();
	}
	
	play void setPlayerFlags() const
	{
		let player = players[consoleplayer];
		player.cmd.buttons |= buttons;
		
		player.mo.PlayerThink();
	}
	
	play void setFlag(Int _flag) const
	{
		buttons |= _flag;
	}
	
	play void unsetFlag(Int _flag) const
	{	
		buttons &= ~(_flag);
	}
}*/