class GZC_Doom64Knockback : GZC_Effect
{
	override void init()
	{
		title = "Doom 64 Knockback";
		Duration = 35 * 60 * 2;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!_event.thing.bMissile) return;
		if (!(_event.thing.target is "PlayerPawn")) return;
		
		_event.thing.target.A_Recoil(2);
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (_event.thing is "PlayerPawn")
		{
			_event.thing.A_Recoil(2);
		}
		
		return false;
	}
}

class GZC_Doom64KnockbackEnemies : GZC_Effect
{
	override void init()
	{
		title = "Doom 64 Knockback for monsters";
		Duration = 35 * 60 * 2;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!_event.thing.bMissile) return;
		if (_event.thing.target is "PlayerPawn") return;
		
		_event.thing.target.A_Recoil(2);
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "PlayerPawn"))
		{
			_event.thing.A_Recoil(2);
		}
		
		return false;
	}
}

class GZC_NegativeDoom64Knockback : GZC_Effect
{
	override void init()
	{
		title = "Negative Doom 64 Knockback";
		Duration = 35 * 60 * 2;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!_event.thing.bMissile) return;
		if (!(_event.thing.target is "PlayerPawn")) return;
		
		_event.thing.target.A_Recoil(-2);
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (_event.thing is "PlayerPawn")
		{
			_event.thing.A_Recoil(-2);
		}
		
		return false;
	}
}

class GZC_NegativeDoom64KnockbackEnemies : GZC_Effect
{
	override void init()
	{
		title = "Negative Doom 64 Knockback for monsters";
		Duration = 35 * 60 * 2;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!_event.thing.bMissile) return;
		if (_event.thing.target is "PlayerPawn") return;
		
		_event.thing.target.A_Recoil(-2);
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (!(_event.thing is "PlayerPawn"))
		{
			_event.thing.A_Recoil(-2);
		}
		
		return false;
	}
}

class GZC_InconsistentDoom64Knockback : GZC_Effect
{
	override void init()
	{
		title = "Inconsistent Doom 64 Knockback";
		Duration = 35 * 60 * 2;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!_event.thing.bMissile) return;
		if (!(_event.thing.target is "PlayerPawn")) return;
		
		double rnd = frandom(-2.0, 2.);
		_event.thing.target.A_Recoil(rnd);
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (_event.thing is "PlayerPawn")
		{
			double rnd = frandom(-2.0, 2.);
			_event.thing.A_Recoil(rnd);
		}
		
		return false;
	}
}

class GZC_FreezeTag : GZC_Effect
{
	override void init()
	{
		title = "Freeze tag";
		Duration = 35 * 60 * 2;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (_event.thing.target is "PlayerPawn")
		{
			_event.thing.damageType = "Ice";
		}
		
		return;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (_event.damageType != "Ice")
		{
			_event.thing.LineAttack(_event.attackangle, _event.attackdistance, _event.attackpitch, _event.damage, "Ice", _event.attackpufftype, _event.DamageFlags, null, _event.attackz, _event.AttackOffsetForward, _event.attackoffsetside); 
			return true;
		}
		
		return false;
	}
}

class GZC_AllAttacksPlasma : GZC_Effect
{
	override void init()
	{
		title = "All attacks are plasma";
		Duration = 35 * 60 * 2;
	}
	
	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (!_event.thing.bMissile) return;
		if (_event.thing is "ArachnotronPlasma" || _event.thing is "PlasmaBall") return;
		
		let miss = _event.thing;
		let owner = _event.thing.target;
		
		owner.A_SpawnProjectile("PlasmaBall", 32, 0, miss.angle, CMF_AIMOFFSET);
		_event.thing.destroy();
		
		return;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (_event.thing is "PlayerPawn")
		{
			PlayerPawn(_event.thing).SpawnPlayerMissile("PlasmaBall");
		}
		else _event.thing.A_SpawnProjectile("PlasmaBall", 32, 0, frandom(-11.25, 11.25), CMF_AIMOFFSET);
		
		return true;
	}
}

class GZC_GunshotsAddEffects : GZC_Effect
{
	override void init()
	{
		title = "Player gunshots randomly add effects";
		Duration = 35 * 60 * 3;
	}
	
	override bool onWorldHitscanPreFired(WorldEvent _event)
	{
		if (_event.thing is "PlayerPawn")
		{
			int rnd = random(0, 49);
			if (!rnd)
			{
				let event = GZC_EventHandler(StaticEventHandler.find('GZC_EventHandler'));
				event.giveEffect(true);
			}
		}
		
		return false;
	}
}

class GZC_ProjectilesAddEffects : GZC_Effect
{
	override void init()
	{
		title = "Player projectiles randomly add effects";
		Duration = 35 * 60 * 3;
	}

	override void onWorldThingSpawn(WorldEvent _event)
	{
		if (!_event.thing) return;
		if (_event.thing.target is "PlayerPawn")
		{
			int rnd = random(0, 29);
			if (!rnd)
			{
				let event = GZC_EventHandler(StaticEventHandler.find('GZC_EventHandler'));
				event.giveEffect(true);
			}
		}
		
		return;
	}
}