class GZC_InconsistentEffectSpeed : GZC_EffectModifier
{
	override void init()
	{
		ignore = false;
		title = "??? effect speed";
		duration = 35 * 30 * 3;
		value = 0.5;
	}
	
	override void onWorldTick()
	{
		if (gametic % 35 != 0) return;
		
		self.value = frandom(0.0, 2.0);
	}
}

class GZC_HalfEffectSpeed : GZC_EffectModifier
{
	override void init()
	{
		ignore = false;
		title = "0.5x effect speed";
		duration = 35 * 30 * 3;
		value = 0.5;
	}
}

class GZC_DoubleEffectSpeed : GZC_EffectModifier
{
	override void init()
	{
		ignore = false;
		title = "2x effect speed";
		duration = 35 * 60 * 6;
		value = 2;
	}
}

class GZC_InconsistentTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "??? timer speed";
		duration = 35 * 30 * 3;
		value = 0.5;
	}
	
	override void onWorldTick()
	{
		if (gametic % 35 != 0) return;
		
		self.value = frandom(0.0, 2.0);
	}
}

class GZC_ZeroTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "Pause timer";
		duration = 35 * 60 * 3;
		value = 0;
	}
}

class GZC_TenthTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "0.1x Timer Speed";
		duration = 35 * 60 * 3;
		value = 0.1;
	}
}

class GZC_ThirdTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "0.3x Timer Speed";
		duration = 35 * 60 * 3;
		value = 0.3;
	}
}

class GZC_HalfTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "0.5x Timer Speed";
		duration = 35 * 60 * 3;
		value = 0.5;
	}
}

class GZC_QuarterTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "0.25x Timer Speed";
		duration = 35 * 60 * 3;
		value = 0.25;
	}
}

class GZC_DoubleTimerSpeed :GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "2x Timer Speed";
		duration = 35 * 60 * 3;
		value = 2;
	}
}

class GZC_TripleTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "3x Timer Speed";
		duration = 35 * 60 * 3;
		value = 3;
	}
}

class GZC_QuadTimerSpeed : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "4x Timer Speed";
		duration = 35 * 60 * 3;
		value = 4;
	}
}

class GZC_FastTimerToHealth : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "More health = Faster Timer";
		duration = 35 * 60 * 3;
	}
	
	override void onWorldTick()
	{
		double count = 0;
		double pool = 0;
		foreach (iplayer : players)
		{
			if (!iplayer.mo) continue;
			else
			{
				pool += iplayer.mo.health;
				count += 1;
			}
		}
		
		double average = pool / count;
		self.value = average / 100.0;
	}
}

class GZC_SlowTimerToHealth : GZC_TimerEffect
{
	override void init()
	{
		ignore = false;
		title = "More health = Slower Timer";
		duration = 35 * 60 * 3;
	}
	
	override void onWorldTick()
	{
		double count = 0;
		double pool = 0;
		foreach (iplayer : players)
		{
			if (!iplayer.mo) continue;
			else
			{
				pool += iplayer.mo.health;
				count += 1;
			}
		}
		
		double average = pool / count;
		self.value = 100.0 / average;
	}
}

class GZC_TimerRunsOnKills : GZC_Effect
{
	override void init()
	{
		ignore = false;
		title = "1 kill = 1 second";
		duration = 35 * 90;
	}
	
	override void onWorldThingDied(WorldEvent _event)
	{
		double timerate = GZC_EventHandler(StaticEventHandler.find('GZC_EventHandler')).calculateTimeRate();
		adjustTimer(35.0 * timerate);
		
		ThinkerIterator it = ThinkerIterator.create('GZC_Effect');
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.type != GZC_Timed) continue;
			
			effect.life += 35.0 * timerate;
		}
	}
}

Class GZC_ResetEffectDuration : GZC_EffectEffect 
{
	override void init()
	{
		ignore = false;
		title = "Reset all effects";
		type = GZC_Instant;
	}
	
	override void onOpen()
	{
		ThinkerIterator it = ThinkerIterator.create('GZC_Effect');
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.getClassName() == self.getClassName()) continue;
			if (effect.life > effect.duration) continue;
			effect.life = 0;
		}
		
	}
}

class GZC_ShuffleEffectLife : GZC_EffectEffect 
{
	override void init()
	{
		ignore = false;
		title = "Randomize all effect progression";
		type = GZC_Instant;
	}
	
	override void onOpen()
	{
		ThinkerIterator it = ThinkerIterator.create('GZC_Effect');
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.getClassName() == self.getClassName()) continue;
			if (effect.type != GZC_Timed) continue;
			if (effect.life > effect.duration) continue;
			
			effect.life = random(0, effect.duration);
		}
	}
}

class GZC_SubtractTimeFromEffects : GZC_EffectEffect
{
	override void init()
	{
		ignore = false;
		type = GZC_Instant;
		title = "Remove # seconds from effects";
	}
	
	override void onOpen()
	{
		int seconds = random(5, 30);
		title = "Remove " .. seconds .. " seconds from effects";
	
		ThinkerIterator it = ThinkerIterator.create('GZC_Effect');
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.getClassName() == self.getClassName()) continue;
			if (effect.type != GZC_Timed) continue;
			if (effect.life > effect.duration) continue;
			
			effect.life -= seconds * 35;
			if (effect.life < 0) effect.life = 0;
		}
	}
}

class GZC_AddTimeFromEffects : GZC_EffectEffect
{
	override void init()
	{
		ignore = false;
		type = GZC_Instant;
		title = "Add # seconds to effects";
	}
	
	override void onOpen()
	{
		int seconds = random(5, 30);
		title = "Add " .. seconds .. " seconds to effects";
	
		ThinkerIterator it = ThinkerIterator.create('GZC_Effect');
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.getClassName() == self.getClassName()) continue;
			if (effect.type != GZC_Timed) continue;
			if (effect.life > effect.duration) continue;
			
			effect.life += seconds * 35;
		}
	}
}

class GZC_KillsReduce : GZC_Effect
{
	override void init()
	{
		title = "Kills reduce effect progression";
		duration = 35 * 60 * 3;
	}
	
	override void onWorldThingDied(WorldEvent _event)
	{
		let def = getDefaultByType(_event.thing.getClass());
		int rate = 35 * max(1, int(def.health / 35));
		
		ThinkerIterator it = ThinkerIterator.create('GZC_Effect');
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.life > effect.duration) continue;
			
			effect.life -= rate;
			if (effect.life < 0) effect.life = 0;
		}
	}
}

class GZC_KillsIncrease : GZC_Effect
{
	override void init()
	{
		title = "Kills increase effect progression";
		duration = 35 * 60 * 3;
	}
	
	override void onWorldThingDied(WorldEvent _event)
	{
		let def = getDefaultByType(_event.thing.getClass());
		int rate = 35 * max(1, int(def.health / 35));
		
		ThinkerIterator it = ThinkerIterator.create('GZC_Effect');
		GZC_Effect effect;
		
		while (effect = GZC_Effect(it.next()))
		{
			if (effect.life > effect.duration) continue;
			effect.life += rate;
		}
	}
}

class GZC_KillsAccelerate : GZC_Effect
{
	override void init()
	{
		title = "Kills accelerate timer";
		duration = 35 * 60 * 3;
	}
	
	override void onWorldThingDied(WorldEvent _event)
	{
		let def = getDefaultByType(_event.thing.getClass());
		adjustTimer(def.health);
	}
}

class GZC_KillsDecelerate : GZC_Effect
{
	override void init()
	{
		title = "Kills decelerate timer";
		duration = 35 * 60 * 3;
	}
	
	override void onWorldThingDied(WorldEvent _event)
	{
		let def = getDefaultByType(_event.thing.getClass());
		adjustTimer(-def.health);
	}
}