class GZC_LootSplosion : GZC_Effect
{
	override void init()
	{
		title = "Lootsplosion";
		desc = "Dramatically multiplies the amout of drops an enemy gives";
		duration = 35 * 60 * 10;
	}
	
	Array<name> items;
	Array<name> monsters;
	override void onOpen()
	{
		items.clear();
		
		foreach (cls : AllActorClasses)
		{
			let def = getDefaultByType(cls);
			if (!def.spawnstate.ValidateSpriteFrame() || !TexMan.getName(def.spawnstate.getSpriteTexture(0)).indexOf("TNT1")) continue;
		
			if (cls is "Inventory") 
			{
				items.push(cls.getClassName());
			}
			if (def.bIsMonster)
			{
				monsters.push(cls.getClassName());
			}
		}
	}
	
	override void onWorldThingDied(WorldEvent _event)
	{
		int rnd = random(3, 5);
		int prevroll = -1;
		
		while (rnd--)
		{
			int rndindex = random(0, items.size() - 1);
			if (rndindex == prevroll) continue;
			
			prevroll = rndindex;
			spawnitem(_event.thing.pos, items[rndindex]);
		}
		
		let ditems = _event.thing.getDropItems();
		if (ditems) 
		{
			while (true)
			{
				spawnitem(_event.thing.pos, ditems.name);
			
				if (ditems.next)
				{
					ditems = ditems.next;
					continue;
				}
				break;
			}
		}
		
		if (!random(0, 99))
		{
			spawnitem(_event.thing.pos, monsters[random(0, monsters.size() - 1)]);
		}
	}
	
	void spawnitem(Vector3 _pos, Name _item, Int _override = -1)
	{
		int rnd = _override == -1 ? random(10, 15) : _override;
		for (int i = 0; i < rnd; ++i)
		{
			let spitem = Actor.spawn(_item, _pos);
			spitem.vel.x = frandom(-10, 10);
			spitem.vel.y = frandom(-10, 10);
			spitem.vel.z = frandom(5, 20);
		}
	}
}

Class GZC_FeelingGenerous : GZC_Effect
{
	override void init()
	{
		title = "IDKFA";
		desc = "Performs the equivalent of using the IDKFA cheat";
		duration = 35 * 30;
		type = GZC_Instant;
	}

	override void onOpen()
	{
		foreach (iplayer : players)
		{
			let player = iplayer.mo;
			if (!player) continue;
			
			player.CheatGive('All', 1);
		}
	}
}

Class GZC_CantHaveShitInDetroit : GZC_Effect
{
	override void init()
	{
		title = "Dude, where's my ...?";
		desc = "Takes awayt a random inventory item from player (assuming it's not critical)";
		duration = 35 * 30;
		type = GZC_Instant;
	}

	override void onOpen()
	{
		Array<String> items;
		items.clear();
	
		ThinkerIterator it = ThinkerIterator.create("Inventory");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			let item = Inventory(mo);
			if (!item) continue;
			if (!item.owner) continue;
			if (!(item.owner is 'PlayerPawn')) continue;
			if (item is 'PuzzleItem' || item is 'Key') continue;
			if (item is 'Fist' || item is 'Pistol') continue;
			
			items.push(item.getClassName());
		}
		
		int rng = random(0, items.size() - 1);
		
		foreach (iplayer : players)
		{
			let player = iplayer.mo;
			if (!player) continue;
			player.TakeInventory(items[rng], 0x7FFFFFFF);
		}
		
		String itemname = (items[rng] == "HexenArmor" ? "Armor" : items[rng]);
		title = "Dude, where's my " .. itemname .. "?";
	}
}

Class GZC_DoubleAmmo : GZC_Effect
{
	override void init()
	{
		title = "sv_infiniteammo -1";
		desc = "Ammunition costs are doubled";
		duration = 35 * 60 * 3;
	}

	override void onWorldTick()
	{
		ThinkerIterator it = ThinkerIterator.create("Weapon");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			if (mo is "weapon" && Inventory(mo).owner)
			{
				let gun = Weapon(mo);
				let def = getDefaultByType(gun.getClass());
				
				gun.AmmoUse1 = def.AmmoUse1 * 2;
				gun.AmmoUse2 = def.AmmoUse2 * 2;
			}
		}
	}
	
	override void onClose()
	{
		ThinkerIterator it = ThinkerIterator.create("Weapon");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			if (mo is "weapon" && Inventory(mo).owner)
			{
				let gun = Weapon(mo);
				let def = getDefaultByType(gun.getClass());
				
				gun.AmmoUse1 = def.AmmoUse1;
				gun.AmmoUse2 = def.AmmoUse2;
			}
		}
	}
}

Class GZC_InfiniteAmmo : GZC_Effect
{
	override void init()
	{
		title = "sv_infiniteammo 1";
		desc = "Infinite ammo";
		duration = 35 * 60 * 3;
	}

	override void onWorldTick()
	{
		ThinkerIterator it = ThinkerIterator.create("Actor");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			if (mo is "weapon" && Inventory(mo).owner)
			{
				let gun = Weapon(mo);
				gun.AmmoUse1 = 0;
				gun.AmmoUse2 = 0;
				gun.bAmmo_Optional = true;
			}
		}
	}
	
	override void onClose()
	{
		ThinkerIterator it = ThinkerIterator.create("Actor");
		Actor mo;
		
		while (mo = Actor(it.next()))
		{
			if (mo is "weapon" && Inventory(mo).owner)
			{
				let gun = Weapon(mo);
				let def = getDefaultByType(gun.getClass());
				
				gun.AmmoUse1 = def.AmmoUse1;
				gun.AmmoUse2 = def.AmmoUse2;
				gun.bAmmo_Optional = def.bAmmo_Optional;
			}
		}
	}
}

Class GZC_FastWeapons : GZC_Effect
{
	override void init()
	{
		title = "sv_fastweapons 2";
		desc = "All weapon frame tics are set to 1";
		duration = 35 * 60 * 3;
	}

	override void onWorldTick()
	{
		foreach (iplayer : players)
		{
			let player = iplayer;
			if (!player.mo) continue;
		
			for (PSprite sprite = player.psprites; sprite != null; sprite = sprite.next)
			{
				if (sprite.tics > 1) sprite.tics = 1;
			}
		}
	}
}

Class GZC_NegativeFastWeapons : GZC_Effect
{
	override void init()
	{
		title = "sv_fastweapons -2";
		desc = "All weapon frame tics are doubled";
		duration = 35 * 60;
	}

	Array<state> prevState;
	
	override void onOpen()
	{
		prevState.clear();
		prevState.reserve(16);
	}
	
	override void onWorldTick()
	{
		int index = -1;
		foreach (iplayer : players)
		{
			let player = iplayer;
			if (!player.mo) return;
			
			if (!player.psprites.CurState) continue;
			if (player.psprites.CurState != prevState[player.mo.PlayerNumber()])
			{
				prevState[player.mo.PlayerNumber()] = player.psprites.CurState;
				
				for (PSprite sprite = player.psprites; sprite != null; sprite = sprite.next)
				{	
					sprite.tics *= 2;
				}
			}
		}
	}
}

Class GZC_RandomWeaponFrameDuration : GZC_Effect
{
	override void init()
	{
		title = "sv_fastweapons ???";
		desc = "All weapon frame tics are randomized";
		duration = 35 * 60 * 2;
	}

	Array<state> prevState;
	
	override void onOpen()
	{
		prevState.clear();
		prevState.reserve(16);
	}
	
	override void onWorldTick()
	{
		PlayerInfo player = players[consoleplayer];
		
		foreach (iplayer : players)
		{
			let player = iplayer;
			if (!player.mo) continue;
			
			if (player.psprites.CurState != prevState[player.mo.PlayerNumber()])
			{
				prevState[player.mo.PlayerNumber()] = player.psprites.CurState;
				int tics = random(1, 10);
				for (PSprite sprite = player.psprites; sprite != null; sprite = sprite.next)
				{	
					sprite.tics = tics;
				}
			}
		}
	}
}

Class GZC_InventorySickness : GZC_Effect
{
	override void init()
	{
		title = "Inventory sickness";
		desc = "Forces the player to vomit their entire inventory. You can pick it back up after.";
		duration = 35 * 10;
	}
	
	override void onOpen()
	{
		foreach (iplayer : players)
		{
			let player = iplayer.mo;
			if (!player) continue;
			player.bPickup = false;
			player.A_StartSound("JOSH/BELCH", Chan_Auto);
		}
	}

	override void onWorldTick()
	{
		foreach (iplayer : players)
		{
			let player = iplayer.mo;
			if (!player) continue;
			let item = player.inv;
			actor newitem;
		
			for (inventory item = player.inv; item != null; item = item.inv)
			{
				if (item is "Fist" || item is "Doggie" || item is "beak") continue;
				else
				{
					Vector3 newpos = player.pos;
					newpos.z += 20;
					if (item is "weapon")
					{
						let gun = weapon(item);
						if (gun.ammo1)
						{
							if (player.countInv(gun.ammo1.getClassName()))
							{
								string ammotype = gun.ammo1.getClassName();
								newitem = Actor.spawn(ammotype, newpos);
								player.takeInventory(gun.ammo1.getClassName(), inventory(newitem).amount);
								break;
							}
						}	
						if (gun.ammo2)
						{
							if (player.countInv(gun.ammo2.getClassName()))
							{
								string ammotype = gun.ammo2.getClassName();
								newitem = Actor.spawn(ammotype, newpos);
								player.takeInventory(gun.ammo2.getClassName(), inventory(newitem).amount);
								break;
							}	
						}
						string guntype = item.getClassName();
						newitem = Actor.spawn(guntype, newpos);
						player.takeInventory(guntype, 1);
						break;
					}
					if (item is "key")
					{
						string keytype = item.getClassName();
						newitem = Actor.spawn(keytype, newpos);
						player.takeInventory(keytype, 1);
						break;
					}
				}
			}
		
			if (newitem)
			{
				newitem.thrust(5 + random(0, 10), player.angle + random(-15, 15));
			}
		}
	}
	
	override void onClose()
	{
		foreach (iplayer : players)
		{
			let player = iplayer.mo;
			if (!player) continue;
			
			player.bPickup = true;
		}
	}
}

Class GZC_TakeAllKeysAway : GZC_Effect
{
	override void init()
	{
		title = "Can't find my keys!";
		desc = "Keys are temporarily taken away from the player";
		duration = 35 * 90;
	}
	
	Array<GZC_ItemToken> items;
	
	override void onOpen()
	{
		items.clear();
	}

	override void onWorldTick()
	{
		foreach (iplayer : players)
		{
			let player = iplayer.mo;
			if (!player) continue;
		
			for (inventory item = player.inv; item != null; item = item.inv)
			{
				if (!(item is "key")) continue;
				
				items.push(GZC_ItemToken.create(player, item.getClassName(), 1));
				
				player.takeInventory(item.getClassName(), 1);
			}
		}
	}
	
	override void onClose()
	{
		foreach (token : items) token.restore();
	}
}

Class GZC_GiveRandomInventory : GZC_Effect
{
	override void init()
	{
		title = "Give a random item";
		desc = "Awards player with random item";
		duration = 35 * 30;
		type = GZC_Instant;
	}
	
	Array<Class<Actor> > items;
	
	override void onOpen()
	{
		items.clear();
		
		foreach(thing : AllActorClasses)
		{
			let def = getDefaultByType(thing);
			if (!def.spawnstate.ValidateSpriteFrame() || !TexMan.getName(def.spawnstate.getSpriteTexture(0)).indexOf("TNT1")) continue;
			if (thing is "inventory") items.push(thing);
		}
		
		int itemrng = random(0, items.size() - 1);
		let select = items[itemrng];
		let def = Inventory(getDefaultByType(select));
		int countrng = random(1, def.MaxAmount);
		
		foreach (iplayer : players)
		{
			if (!iplayer.mo) continue;
			iplayer.mo.GiveInventory(def.getClassName(), countrng);
		}
		
		title = "Give " .. countrng .. " " .. def.getClassName() .. (countrng > 1 ? "s" : "");
	}
}

Class GZC_GiveRandomWeapon : GZC_Effect
{
	override void init()
	{
		title = "Give a random weapon";
		desc = "Awards player with a random weapon";
		duration = 35 * 30;
		type = GZC_Instant;
	}
	
	Array<Class<Actor> > items;
	
	override void onOpen()
	{
		items.clear();
		
		foreach(thing : AllActorClasses)
		{
			let def = getDefaultByType(thing);
			if (!def.spawnstate.ValidateSpriteFrame() || !TexMan.getName(def.spawnstate.getSpriteTexture(0)).indexOf("TNT1")) continue;
			if (thing is "weapon") items.push(thing);
		}
		
		int itemrng = random(0, items.size() - 1);
		let select = items[itemrng];
		
		let def = Weapon(getDefaultByType(select));
		
		foreach (iplayer : players)
		{
			let player = iplayer.mo;
			if (!player) continue;
			
			player.GiveInventory(def.getClassName(), 1);
			player.A_SelectWeapon(def.getClassName());
		}
		
		title = "Give " .. def.getClassName();
	}
}