version "4.10"

#include "GZChaos/GZC_Events.zsc"
#include "GZChaos/GZC_StaticEvents.zsc"
#include "GZChaos/GZC_Utils.zsc"

#include "GZChaos/GZC_OptionsMenu.zsc"

#include "GZChaos/screendrawing/GZC_Drowsy.zsc"
#include "GZChaos/screendrawing/GZC_InfoDisplay.zsc"
#include "GZChaos/screendrawing/GZC_PortraitMode.zsc"
#include "GZChaos/screendrawing/GZC_RearViewMirror.zsc"
#include "GZChaos/screendrawing/GZC_PongDrawer.zsc"
#include "GZChaos/screendrawing/GZC_TimerBar.zsc"

#include "GZChaos/enemies/Bee.zsc"
#include "GZChaos/enemies/Cyberfuck.zsc"
#include "GZChaos/enemies/JitterSkull.zsc"
#include "GZChaos/enemies/SCP173.zsc"

//Morph actors
#include "GZChaos/enemies/morphs/Zombieman.zsc"
#include "GZChaos/enemies/morphs/Shotgunner.zsc"
#include "GZChaos/enemies/morphs/Chaingunner.zsc"
#include "GZChaos/enemies/morphs/DoomImp.zsc"
#include "GZChaos/enemies/morphs/ExplosiveBarrel.zsc"
#include "GZChaos/enemies/morphs/GreatGodImp.zsc"
#include "GZChaos/enemies/morphs/Kamikazi.zsc"
#include "GZChaos/enemies/morphs/BetaSkull.zsc"
#include "GZChaos/enemies/morphs/Cacodemon.zsc"

#include "GZChaos/morphs/DogMode.zsc"

#include "GZChaos/weapons/Coffee.zsc"

#include "GZChaos/events/AudioEffects.zsc"
#include "GZChaos/events/DecorationEffects.zsc"
#include "GZChaos/events/EnemyEffects.zsc"
#include "GZChaos/events/GameEffects.zsc"
#include "GZChaos/events/InventoryEffects.zsc"
#include "GZChaos/events/MapEffects.zsc"
#include "GZChaos/events/MetaEffects.zsc"
#include "GZChaos/events/PickupEffects.zsc"
#include "GZChaos/events/PlayerEffects.zsc"
#include "GZChaos/events/ShaderEffects.zsc"
#include "GZChaos/events/SpriteEffects.zsc"
#include "GZChaos/events/TimerEffects.zsc"

//Morph events
#include "GZChaos/events/EnemyReplacements/EnemyMorphEvent.zsc"
#include "GZChaos/events/EnemyReplacements/Cacodemon.zsc"
#include "GZChaos/events/EnemyReplacements/Zombiemen.zsc"
#include "GZChaos/events/EnemyReplacements/Shotgunner.zsc"
#include "GZChaos/events/EnemyReplacements/Chaingunner.zsc"
#include "GZChaos/events/EnemyReplacements/DoomImp.zsc"