class GZC_ExplosiveBarrel : MorphedMonster
{
	Default
	{
		Health 20;
		Radius 10;
		Height 42;
		+SOLID
		+SHOOTABLE
		+NOBLOOD
		+ACTIVATEMCROSS
		+DONTGIB
		+NOICEDEATH
		+OLDRADIUSDMG
		DeathSound "world/barrelx";
		Obituary "$OB_BARREL";
	}
	States
	{
	Spawn:
		BAR1 AB 6;
		Loop;
	Death:
		BEXP A 5 BRIGHT;
		BEXP B 5 BRIGHT A_Scream;
		BEXP C 5 BRIGHT;
		BEXP D 10 BRIGHT A_Explode;
		BEXP E 10 BRIGHT;
		TNT1 A 1050 BRIGHT A_BarrelDestroy;
		TNT1 A 5 A_Respawn;
		stop;
	}
}

class GZC_DecorativeBarrel : MorphedMonster
{
	Default
	{
		Radius 10;
		Height 42;
		ProjectilePassHeight -16;
		+Solid;
		-Shootable;
		+DontThrust;
	}
	States
	{
	Spawn:
		BAR1 C -1;
		stop;
	}
}